### ISSUE TITLE
Allow Cross-Origin-Requests on API

### ISSUE THREAD

**Issue by TKAB** [ragnarlonn/pushdata.io#13]
I'm trying to do a visualization of data in JSFiddle, but I get a `Origin https://fiddle.jshell.net is not allowed by Access-Control-Allow-Origin`.

When I'm trying to funnel the data through _webtask.io_ (lambda function on node.js), there's an error `Error: write EPROTO 140550543607616:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802`.
Not sure if the two are related.

**Comment by pushdata-io** [comment]
@TKAB Sorry, try the jsfiddle now!  I've added CORS headers for the API end points.

As for the SSL error, it sounds like it may be something else. I don't know how to use webtask.io though - could you share what type of script/task you're running there, that causes the error?  (I.e. it'd be useful if I knew how to replicate the problem)

Regards,

  /Ragnar

**Comment by TKAB** [comment]
CORS works. Thanks! Awesome response time.

Thomas

**Comment by wizzard0** [comment]
@TKAB SSL23_GET_SERVER_HELLO is a node 8.6 bug, https://github.com/nodejs/node/issues/16196, simple workaround is
```
require("tls").DEFAULT_ECDH_CURVE = "auto" // https://github.com/nodejs/node/issues/16196
```

**Comment by ragnarlonn** [comment]
@wizzard0 Thanks!  That means I'm closing this issue. Please reopen (or create a new issue) if the workaround isn't working!

**Comment by TKAB** [comment]
Thanks! Will try to fix this way.
