### ISSUE TITLE
User dashboard: add "set timezone" option

### ISSUE THREAD

**Issue by ragnarlonn** [ragnarlonn/pushdata.io#5]
Users want to see their data timestamped in their own TZ

Will add dependency on moment.js - https://api.highcharts.com/highcharts/time.timezone

**Comment by wizzard0** [comment]
Would actually be awesome to see both UTC and local time under the points (or in the tooltip)

**Comment by vincent-gh** [comment]
Hi,
+1 for this feature request :)
It would be great to be able to set the timezone for the charts, so to be able to see the data charts in your own local time.
Is this planned for the near future?

**Comment by ragnarlonn** [comment]
@wizzard0 @vincent-gh Ok, now there is a timezone option in the user settings, that control what timezone timestamps are displayed in. I like the idea about displaying UTC also, in the tooltips, but will save that idea for the next overhaul of the dashboard.

**Comment by vincent-gh** [comment]
Great! Thanks a lot!
Vincent

________________________________
